typography_spectrum: 0.932751854415983
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4811920002102852
  lightness: 0.03862537979148328
  saturation: 0.4509005125146359
  rhythmicContrast: 0.6874399615917355
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.69927380932495
analytics:
  google: null
  facebook: null
  twitter: null
name: Robert Cates
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Robert Cates
description: 'Singer-songwriter, Vocal Coach, Worship Leader'
purpose: []
